{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red255\green238\blue149;\red21\green102\blue47;}
{\*\expandedcolortbl;;\cssrgb\c100000\c94118\c64706;\cssrgb\c7451\c46667\c23922;}
\margl1440\margr1440\vieww28600\viewh17480\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs24 \cf2 \cb3 \CocoaLigature0 ---\
- name: installing and launching filebeat\
  hosts: webservers\
  become: yes\
  tasks:\
\
  - name: download filebeat deb\
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb\
 \
  - name: install filebeat deb\
    command: dpkg -i filebeat-7.4.0-amd64.deb \
\
  - name: drop in filebeat.yml \
    copy:\
      src: /etc/ansible/files/filebeat-config.yml\
      dest: /etc/filebeat/filebeat.yml        \
\
  - name: enable and configure system module\
    command: filebeat modules enable system\
\
  - name: setup filebeat\
    command: filebeat setup\
\
  - name: start filebeat service\
    command: service filebeat start}