{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red255\green238\blue149;\red21\green102\blue47;}
{\*\expandedcolortbl;;\cssrgb\c100000\c94118\c64706;\cssrgb\c7451\c46667\c23922;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs24 \cf2 \cb3 \CocoaLigature0 ---\
- name: Configure Elk VM with Docker\
  hosts: elkservers\
  remote_user: elk\
  become: true\
  tasks:\
    # Use apt module\
    - name: Install docker.io\
      apt:\
        update_cache: yes\
        name: docker.io\
        state: present\
\
      # Use apt module\
    - name: Install pip3\
      apt:\
        force_apt_get: yes\
        name: python3-pip\
        state: present\
\
      # Use pip module\
    - name: Install Docker python module\
      pip:\
        name: docker\
        state: present\
\
      # Use sysctl module\
    - name: Use more memory\
      sysctl:\
        name: vm.max_map_count\
        value: "262144"\
        state: present\
        reload: yes\
\
      # Use docker_container module\
    - name: download and launch a docker elk container\
      docker_container:\
        name: elk\
        image: sebp/elk:761\
        state: started\
        restart_policy: always\
        published_ports:\
          - 5601:5601\
          - 9200:9200\
          - 5044:5044}