{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red255\green238\blue149;\red21\green102\blue47;}
{\*\expandedcolortbl;;\cssrgb\c100000\c94118\c64706;\cssrgb\c7451\c46667\c23922;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs24 \cf2 \cb3 \CocoaLigature0 ---\
- name: Config Web VM with Docker\
  hosts: webservers\
  become: true\
  tasks:\
    - name: docker.io\
      apt:\
        update_cache: yes\
        name: docker.io\
        state: present\
\
    - name: Install pip3\
      apt:\
        name: python3-pip\
        state: present\
\
    - name: Install Docker python module\
      pip:\
        name: docker\
        state: present\
\
    - name: download and launch a docker web container\
      docker_container:\
        name: dvwa\
        image: cyberxsecurity/dvwa\
        state: started\
        restart_policy: always\
        published_ports: 80:80\
\
    - name: Enable docker service\
      systemd:\
        name: docker\
        enabled: yes}